### ISSUE TITLE
Add Merchant API

### ISSUE THREAD

**Issue by gabizou** [GlowstoneMC/Glowkit-Legacy#12]
I know Glowstone is incomplete, but, it can be useful to at least add the notion of trading with Merchants into Glowkit.

I used to have a related PR for this: https://github.com/Bukkit/Bukkit/pull/1077

As you can see when reading the PR, it went through many iterations and changes, and finally was very close to being accepted before the Bukkit shutdown.

**Comment by turt2live** [comment]
If @SpaceManiac is okay with it, I can add it to the existing list of PRs that are "useless" without implementation (#3).

**Comment by turt2live** [comment]
Closing as further discussion is best held at #55
